### ISSUE TITLE
Uncaught TypeError: Cannot read property 'browser' of undefined in browser

### ISSUE THREAD

**Issue by zombie-go** [nhnent/tui.calendar#119]
## Version
Latest version via CDN;

## Development Environment
Windows 10, Chrome ver. 66.0.3359.181

## Current Behavior
Simple test page:

```
<!DOCTYPE html>
<html>
    <head>
        <script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
        <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.css" />
    </head>

    <body>
        <div id='calendar'></div>
        <!--<script src="./Calendar.js"></script>-->
        <script>
        var Calendar = tui.Calendar
                debugger
                var calendar = new Calendar('#calendar',{
                    defaultView: 'month',
                    taskView: true,
                    template: {
                        monthGridHeader: function(model) {
                          var date = new Date(model.date);
                          var template = '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate() + '</span>';
                          return template;
                        }
                    }
                });
        </script>
    </body>  
</html>
```

## Expected Behavior
I get this error:

**Uncaught TypeError: Cannot read property 'browser' of undefined** in tui-calendar.js line 3632 (var browser = util.browser,)

**Comment by youjung-hong** [comment]
Hello @zombie-go 

1. This is due to missing `tui-code-snippet` dependency.
It was omitted at README and now we updated the README.
Add this code on your file. then it will not throw any errors.
```
<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
```

2. But, there is one thing you have to do.
Setting the `#calendar` elements height is needed.'

Month Calendar is composed to two part:
- DayGrid: shows name of weekday(Mon, Tue, Wed, ...)
- Other(let's call it DateGrid): shows date of month(1, 2, 3, ...(31))

DayGrid height is set to 31px by default.
However the DateGrid part height is determined like this: `height of #calendar - height of DayGrid(31px default)`
If #calendar height is not larger than DayGrid height, the DateGrid will not appear like this.

| No Height | Has Height |
| --- | --- |
| ![2018-05-23 10 49 50](https://user-images.githubusercontent.com/13758710/40399525-c92a34f8-5e78-11e8-8df3-8e868f1e1737.png) | ![2018-05-23 10 50 21](https://user-images.githubusercontent.com/13758710/40399528-ce055f5c-5e78-11e8-972c-ac998b323974.png) |

So, please add calendar height.

Thank you!

**Comment by zombie-go** [comment]
It works fine now.
Thank you!

**Comment by noelpicinich** [comment]
Heads up, this worked for me but only after I moved the script statement for the tui-code-snippet above the script for tui-calendar!
