### ISSUE TITLE
State is always Busy

### ISSUE THREAD

**Issue by Ashwin-Kapes** [nhnent/tui.calendar#228]
## Version
1.7.0

## Development Environment
Chrome Browser, Hosted on cloud(Digital Ocean)

## Current Behavior
In ScheduleList object state that I'm receiving is "Free" But on calendar it's always "Busy"

```
[
{ 
bgColor: "#9e5fff"
borderColor: "#9e5fff"
calendarId: "1"
category: "time"
color: "#ffffff"
end: null
id: "1"
isAllDay: true
isReadOnly: true
location: ""
start: "2018-10-02 09Z"
state: "Free" // This is displayed always Busy
title: "Mahatma Gandhi Jayanti" 
}
]

```

## Expected Behavior
If I'm receiving state: "Free" then "Free" should be displayed in popup description.

**Comment by supertrip86** [comment]
I'm interested as well. The state of every newly created schedule won't change from "busy" to "free"
Here is where the problem lies:

`    'popupDetailState-tmpl': function(schedule) {
        return schedule.state || 'Busy';
    }`

You can find these lines in tui-calendar.js.
Basically schedule.state is not defined, and the program assigns "Busy" as default state.
